require("plugins-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.neotree")
require("plugins.statusline")
require("plugins.whichkey")
require("plugins.noice")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autocomplete")
require("plugins.neogit")
